name: latmod4
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.4.1
  get: ^4.6.6
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  flutter: 
    sdk: flutter
  shared_preferences: ^2.2.2
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.1.0
  appwrite: ^11.0.1
  http: ^1.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

