// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChNOmUb_hQ3lK1kOj3thjiAtDKTsjCJfE',
    appId: '1:1005118234190:web:1240a809e7c7e715406d1f',
    messagingSenderId: '1005118234190',
    projectId: 'latmodul4',
    authDomain: 'latmodul4.firebaseapp.com',
    storageBucket: 'latmodul4.appspot.com',
    measurementId: 'G-6T4YPE02NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY7-owksRCYFp6zy3kKGH6RqahIapMIIA',
    appId: '1:1005118234190:android:7973343bc9da24e8406d1f',
    messagingSenderId: '1005118234190',
    projectId: 'latmodul4',
    storageBucket: 'latmodul4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8VUYs4GKEVLNAjQT__udV2MWC5KXcOhY',
    appId: '1:1005118234190:ios:651e19376c9778b1406d1f',
    messagingSenderId: '1005118234190',
    projectId: 'latmodul4',
    storageBucket: 'latmodul4.appspot.com',
    iosBundleId: 'com.praktikum.latmod4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8VUYs4GKEVLNAjQT__udV2MWC5KXcOhY',
    appId: '1:1005118234190:ios:7918dbbde52125f3406d1f',
    messagingSenderId: '1005118234190',
    projectId: 'latmodul4',
    storageBucket: 'latmodul4.appspot.com',
    iosBundleId: 'com.praktikum.latmod4.RunnerTests',
  );
}
